// milk.script
host = getHostname();
while (true) {
    SerSec = getServerSecurityLevel(host);
    MinSec = getServerMinSecurityLevel(host);

    SerCash = getServerMoneyAvailable(host);
    MaxCash = getServerMaxMoney(host);

    if (SerSec > MinSec) {
        weaken(host);
    } else {
        if (SerCash < MaxCash) {
            grow(host);
        } else {
            hack(host);
        }
    }
}
