// milk.script
host = getHostname();
while (true) {
    SerSec = getServerSecurityLevel(host);
    MinSec = getServerMinSecurityLevel(host);

    SerCash = getServerMoneyAvailable(host);
    MaxCash = getServerMaxMoney(host);

    if (SerSec > MinSec) {
    	exec("arw.script", "home", 200, host)
    } else {
        if (SerCash < MaxCash) {
        	exec("arg.script", "home", 200, host)
        } else {
            hack(host);
        }
    }
}
