// ramless_hacker.script
// Hack if seclev is lowest and money is max.
// Hack until you have removed 10% of the max money.

serv = args[0];
tprint(getHostname() + ": RAMLessHacker Starting  " + serv); 

// Targets RAM
ServRAM = getServerRam(serv);
ServRAMTot = ServRAM[0];

// Home RAM to devote to RAMLess targets
// Be carefull here you could over hack the target easily
MyRAM = 1024;

// ramless Hacker RAM
ramless_hackerRAM = getScriptRam("ramless_hacker.script");
HackRAM = getScriptRam("h.script");
WeakenRAM = getScriptRam("w.script");
GrowRAM = getScriptRam("g.script");

// When to stop hacking. 0.9 hacks to 90% (it takes 10% out)
MaxCash = getServerMaxMoney(serv);
DrainGoal = (MaxCash * 0.9);

// Minimum Security level on the target
MinSec = getServerMinSecurityLevel(serv);

// Grow Threads
Gthreads = Math.round(MyRAM / GrowRAM);
// Weaken Threads
Wthreads = Math.round(MyRAM / WeakenRAM);
// Hack Threads
//Hthreads = Math.round(32 / HackRAM);
Hthreads = 32
// === All above should be constant
// === All below are dynamic
while (true) {
    sleep(2000);
    // Target Host stats

    // Server Cash
    SerCash = getServerMoneyAvailable(serv);

    // Server Sec
    SerSec = getServerSecurityLevel(serv);

    // Target Host stats end

// === End Vars

    // Do all the things
    if (SerSec > MinSec) {
        run("w.script", Wthreads, serv);
    } else if (SerCash < MaxCash) {
        run("g.script", Gthreads, serv);
    } else {
        while (getServerMoneyAvailable(serv) > DrainGoal) {
            run("h.script", Hthreads, serv);
        }
    }
}